import * as fs from 'node:fs';
import * as path from 'node:path';

const projectRoot = path.resolve(process.cwd());
const inputFile = path.join(projectRoot, 'src', 'lib', 'storyblok', 'resources', 'types', 'storyblok-components.d.ts');
const outputDir = path.join(projectRoot, 'src', 'lib', 'storyblok', 'registry');
const outputFile = path.join(outputDir, 'StoryblokBlok.ts');

// ✅ Ensure directory exists
fs.mkdirSync(outputDir, { recursive: true });

// ✅ Read the input file
if (!fs.existsSync(inputFile)) {
  console.error(`❌ Input file not found: ${inputFile}`);
  process.exit(1);
}

const fileContent = fs.readFileSync(inputFile, 'utf-8');

// Match all exported interfaces
const interfaceRegex = /export interface (\w+)/g;
const matches = [...fileContent.matchAll(interfaceRegex)];
const interfaceNames = matches.map((m) => m[1]);

if (interfaceNames.length === 0) {
  console.error('No interfaces found in storyblok-components.d.ts');
  process.exit(1);
}

// ✅ Generate import + union type
const importStatement = `import { ${interfaceNames.join(', ')} } from '@/lib/storyblok/resources/types/storyblok-components';\n`;
const unionType = `// AUTO-GENERATED FILE - DO NOT EDIT
// Generated from source file: /src/lib/storyblok/resources/types/storyblok-components.d.ts
// Generated by script .dev/storyblok/generate-union-type.ts
${importStatement}
export type StoryblokBlok = ${interfaceNames.join(' | ')};\n`;

// ✅ Overwrite file (delete if exists)
if (fs.existsSync(outputFile)) {
  fs.unlinkSync(outputFile); // Remove old file
}

fs.writeFileSync(outputFile, unionType);
console.log(`✅ Generated StoryblokBlok union type with ${interfaceNames.length} interfaces at ${outputFile}`);
