import { Box, Code, Text } from '@mantine/core';
import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import Card from '../components/Card/Card';
import Grid from '../components/Grid/Grid';
import styles from './index.module.scss';

const Home: NextPage = () => {
  return (
    <Box component="main" className={styles.mainLevel1}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Box component="main" className={styles.mainLevel2}>
        <Text className={styles.welcome}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </Text>

        <Text className={styles.getStarted}>
          Get started by editing <Code className={styles.code}>pages/index.tsx</Code>
        </Text>

        <Grid>
          <Card
            title="Documentation &rarr;"
            description="Find in-depth information about Next.js features and API."
            link="https://nextjs.org/docs"
          />
          <Card
            title="Learn &rarr;"
            description="Learn about Next.js in an interactive course with quizzes!"
            link="https://nextjs.org/learn"
          />
          <Card
            title="Examples &rarr;"
            description="Discover and deploy boilerplate example Next.js projects."
            link="https://nextjs.org/examples"
          />
          <Card
            title="Deploy &rarr;"
            description="Instantly deploy your Next.js site to a public URL with Vercel."
            link="https://vercel.com/import?filter=next.js&utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          />
        </Grid>
      </Box>

      <Box component="footer" className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <Box component="span" className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </Box>
        </a>
      </Box>
    </Box>
  );
};

export default Home;
